version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/workflows'
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: '/.github/workflows'
    schedule:
      interval: monthly
